---
title: "Breast Cancer Prediction with R"
output: html_notebook
---
```{r}

data <- read.csv("breast cancer.csv",header=FALSE, sep=",")

str(data)
head(data)
summary(data)

```

```{r}


names(data) <- c('Id','Cl_thickness','Cell_size','Cell_shape','Marg_adhesion','Epith_c_size','Bare_nuclei','Bl_cromat','Normal_nucleoli','Mitoses','Class')
data$Class[data$Class == 2] = 0
data$Class[data$Class == 4] = 1
```

```{r}
summary(data)
sum(data == '?')
```

```{r}
data[data == '?'] <- 0
data$Bare_nuclei <- as.numeric(data$Bare_nuclei)
data$Bare_nuclei[data$Bare_nuclei == 0 ] <- mean(data$Bare_nuclei, na.rm =TRUE)
```

```{r}
data$Id <- NULL
str(data)
summary(data)

```
```{r}

library(caTools)
set.seed(123)    
split=sample.split(data, SplitRatio = 0.8)
training_set=subset(data,split==TRUE)
test_set=subset(data,split==FALSE)
dim(training_set) 
```

```{r}


training_set[,1:9] = scale(training_set[,1:9])
test_set[,1:9] = scale(test_set[,1:9])

```
```{r}
Classifier = glm(formula = Class ~ ., 
                 family = binomial, 
                 data = training_set)
```

```{r}
prob_pred = predict(Classifier, type = 'response', newdata = test_set[1:9])
prob_pred
y_pred = ifelse(prob_pred > 0.5, 1, 0)
y_pred
```
```{r}
cm = table(test_set[,10], y_pred)
cm
```
```{r}
accuracy = (cm[1,1] + cm[2,2]/(cm[1,1] + cm[2,2]+ cm[1,2] + cm[2,1]))
accuracy
```

```{r}
library(caret)
folds = createFolds(training_set$Class, k = 10)
CrossValidation = lapply(folds, function(x){
  training_fold = training_set[-x,] # taking all the training set but without the fold
  test_fold = training_set[x,]
  Classifier = glm(formula = Class ~ ., 
                   family = binomial, 
                   data = training_fold)
  prob_pred = predict(Classifier, type = 'response', newdata = test_fold[1:9])
  y_pred = ifelse(prob_pred > 0.5, 1, 0)
  cm = table(test_fold[,10], y_pred)
  accuracy = ((cm[1,1] + cm[2,2])/(cm[1,1] + cm[2,2]+ cm[1,2] + cm[2,1]))
  return(accuracy)
})
CrossValidation
accuracies = mean(as.numeric(CrossValidation))
accuracies
```

```{r}
library(caret)
classifier = train(form = as.factor(Class) ~ ., data = training_set, method='glm')
classifier
classifier$bestTune
```

```{r}

summary(Classifier)
summ = summary(Classifier)
p_values = summ$coefficients[,4]
p_values =  p_values[p_values>0.5]
imp_cols = names(p_values)
imp_cols
set = data
plot(set)
```



